// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models;

public partial class CarRentalExampleContext : DbContext
{
    public CarRentalExampleContext(DbContextOptions<CarRentalExampleContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Booking> Bookings { get; set; }

    public virtual DbSet<Car> Cars { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Booking>(entity =>
        {
            entity.HasKey(e => e.BookingId).HasName("PK__Booking__73951ACDDD83759C");

            entity.ToTable("Booking");

            entity.Property(e => e.BookingId).HasColumnName("BookingID");
            entity.Property(e => e.BookingStatus)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Pending")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Bookings_Status");
            entity.Property(e => e.CarId).HasColumnName("CarID");
            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.EndDate).HasColumnType("datetime");
            entity.Property(e => e.PaymentType)
                .IsRequired()
                .HasMaxLength(20)
                .HasDefaultValue("Not Paid")
                .HasAnnotation("Relational:DefaultConstraintName", "DF_Payment_Type");
            entity.Property(e => e.StartDate).HasColumnType("datetime");

            entity.HasOne(d => d.Car).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CarId)
                .HasConstraintName("FK_Car_Bookings");

            entity.HasOne(d => d.Customer).WithMany(p => p.Bookings)
                .HasForeignKey(d => d.CustomerId)
                .HasConstraintName("FK_Customer_Bookings");
        });

        modelBuilder.Entity<Car>(entity =>
        {
            entity.HasKey(e => e.CarId).HasName("PK__Cars__68A0340E7B8AB557");

            entity.Property(e => e.CarId).HasColumnName("CarID");
            entity.Property(e => e.CarColourway)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CarMake)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CarModel)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.CarVin).HasMaxLength(17);
            entity.Property(e => e.CarYear)
                .IsRequired()
                .HasMaxLength(4);
        });

        modelBuilder.Entity<Customer>(entity =>
        {
            entity.HasKey(e => e.CustomerId).HasName("PK__Customer__A4AE64B8D6C097D5");

            entity.Property(e => e.CustomerId).HasColumnName("CustomerID");
            entity.Property(e => e.CustomerEmail)
                .IsRequired()
                .HasMaxLength(150);
            entity.Property(e => e.CustomerName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CustomerPhone)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.Customeraddress)
                .IsRequired()
                .HasMaxLength(1050);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}